GeoDienstenCentrum/sass-maven-plugin

.travis.yml
again...
refs: https://github.com/GoogleCloudPlatform/DataflowJavaSDK/commit/242b4c3025b74090e574087d54a2ae46d091e9b7
=> OS-X builds

pom.xml, src/test/java/nl/geodienstencentrum/maven/plugin/sass/compiler/CompilerBenchmarkTest.java
won't merge until test coverage is complete
close #19
=>  jrjackson (or not)

src/main/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintMojo.java, src/main/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintReportGenerator.java, src/main/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintReportMojo.java, src/test/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintMojoTest.java, src/test/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintReportMojoTest.java, src/test/projects/maven-lint-resources-test/pom.xml, src/test/projects/maven-lint-resources-test/src/main/sass/_CoreNavButtons.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_Debug.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_OverviewMap.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_Tooltip.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_Viewer.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_ZoekFormulier.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_ZoomControl.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_colours_and_vars.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_layout.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_mainMenu.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_openlayers.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_siteMenu.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_skipLinks.scss, src/test/projects/maven-lint-resources-test/src/main/sass/_style.scss, src/test/projects/maven-lint-resources-test/src/main/sass/compiled.scss, src/test/projects/maven-lint-resources-test/src/main/sass/print.scss, src/test/projects/maven-lint-resources-test/src/site/site.xml
currently only  `sassSourceDirectory` is supported for specifying sass sources
=> support resources in scss-lint targets

src/main/java/nl/geodienstencentrum/maven/plugin/sass/AbstractSassMojo.java, src/test/java/nl/geodienstencentrum/maven/plugin/sass/compiler/UpdateStylesheetsMojoTest.java, src/test/projects/maven-compass-configuration-file-test/expected_images.css, src/test/projects/maven-compass-configuration-file-test/pom.xml, src/test/projects/maven-compass-configuration-file-test/src/main/resources/compass.rb, src/test/projects/maven-compass-configuration-file-test/src/main/sass/images.sass
I needed a way to specify a compass config file location from the pom.xml, this was the solution.
=> add parameter to specify a `compass.rb` configuration file for compass

pom.xml
=> JRuby 1.7 update

pom.xml
=> update maven libs from 3.3.1 to 3.3.3

pom.xml, src/site/apt/releasenotes.apt.vm
Which has a vulnerability fix for CVE-2015-4020
see jruby/jruby#3030
=> update jruby dependency to 1.7.20.1

appveyor.yml, pom.xml, src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/WatchMojo.java, src/test/java/nl/geodienstencentrum/maven/plugin/sass/compiler/WatchMojoTest.java
close #20 all test pass
close #24 with the new jruby and conditionally having 'listen' polling for changes
=> windows integration testing on AppVeyor

NOTICE, pom.xml
=> upgrade to JRuby 9.0.0.0 final

src/main/java/nl/geodienstencentrum/maven/plugin/sass/AbstractSassMojo.java, src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/UpdateStylesheetsMojo.java, src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/WatchMojo.java, src/main/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintMojo.java, src/main/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintReportMojo.java, src/site/apt/releasenotes.apt.vm, src/test/java/nl/geodienstencentrum/maven/plugin/sass/compiler/UpdateStylesheetsMojoTest.java, src/test/projects/skip-execution-project/pom.xml, src/test/projects/skip-execution-project/src/main/sass/_colours.scss, src/test/projects/skip-execution-project/src/main/sass/_style.scss, src/test/projects/skip-execution-project/src/main/sass/compiled.scss
=> add a skip parameter

.travis.yml
add builds for openjdk7 and  oraclejdk8 on linux
=> Build on other than the default JDK on linux

pom.xml, src/site/apt/releasenotes.apt.vm
=> update Sass to new 3.4.18 release; critical upgrade

pom.xml, src/site/apt/releasenotes.apt.vm
also update some plugins and add a pluginManagment section
=> update Bourbon and SCSS-lint

pom.xml, src/main/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintMojo.java, src/site/apt/releasenotes.apt.vm
and while here update the gem-maven-plugin as well
=> update scss-lint to 0.44.0

.appveyor/set-maven-proxy.ps1, .travis.yml, appveyor.yml
- update maven to 3.3.9
- allow failures on (eol) Oracle Java 7
=> build environment updates

pom.xml, src/site/apt/releasenotes.apt.vm
=> Upgrade JRuby to 9.1.4.0

.travis.yml
Add back openjdk8 build and new oraclejdk9 build on Linux
=> Try oraclejdk9 builds

pom.xml
=> Upgrade to JRuby 9.1.5.0

.travis.yml
this provides testing on Maven 3.2.5 w/ Oracle java 8
=> Multiple maven builds

src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/UpdateStylesheetsMojo.java
=> add css filter at destination when checking buildrequired

pom.xml
Upgrade to JRuby 9.1.6.0, see: http://jruby.org/2016/11/09/jruby-9-1-6-0
=> Upgrade to JRuby 9.1.6.0

pom.xml
=> Jruby 9.1.7.0

.travis.yml, pom.xml
=> Maven 3.5.0

pom.xml, src/site/apt/development.apt.vm, src/site/apt/releasenotes.apt.vm
also upgrade scss-lint and the maven-versions plugin
close #153
=> upgrade jruby to 9.1.12.0

.travis.yml, pom.xml, src/site/apt/development.apt.vm, src/site/apt/releasenotes.apt.vm, src/test/projects/maven-bourbon-test/pom.xml
exclude or work around failing tests for now
=> Sass35 test fixes

.travis.yml, pom.xml, src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/WatchMojo.java, src/site/apt/releasenotes.apt.vm, src/test/projects/maven-sass-test/pom.xml
=> Use `sass-listen` instead of `listen` gem for polling on windows

.travis.yml, pom.xml, src/site/apt/releasenotes.apt.vm
- update maven dependencies to 3.5.3
- update Sass to 3.5.6
=> Dependency updates

src/main/java/nl/geodienstencentrum/maven/plugin/sass/AbstractSassMojo.java, src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/UpdateStylesheetsMojo.java, src/main/java/nl/geodienstencentrum/maven/plugin/sass/compiler/WatchMojo.java, src/site/apt/releasenotes.apt.vm
=> mark plugin threadsafe

src/main/java/nl/geodienstencentrum/maven/plugin/sass/report/SCSSLintMojo.java
=> Do not execute lint on empty source list
